services:
  app1:
    image: ${DOCKER_REGISTRY-}app1
    networks: 
      - mynetwork
    build:
      context: .
      dockerfile: app1/Dockerfile
    ports: 
       - "5432:80"
    environment:
      - ASPNETCORE_URLS=http://*:80
    depends_on: 
      - rabbitmq

  app2:
    image: ${DOCKER_REGISTRY-}app2
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: app2/Dockerfile
    ports: 
       - "5433:80"
    environment:
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: 1234!
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork: